name: Validate XML
on:
  pull_request:
    types: [opened, reopened, edited]
    branches: ['master']
  workflow_dispatch:
jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate XML
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          xmllint --noout --format anime-list-master.xml anime-movieset-list.xml
